
name: Upload
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Upload:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with: 
        name: Assets
        path: build/ipa/

